spring:
  ## VARIABLES DE ENTORNO ##
  datasource:
    url: jdbc:mysql://localhost:3306/grupo-17-oo2-2023
    username: root
    password: LooneyTunes12
#    password: root
    #######################
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true